[package]
name = "ikev2_localpipe"
version = "0.1.0"
edition = "2021"

[dependencies]
# Linux 用 zbus 调用 NetworkManager D-Bus
zbus = "3.15.2"
zvariant = "3.15.2"

# Linux 下需要异步运行时
tokio = { version = "1", features = ["full"] }

# 跨平台运行时不需要额外依赖，macOS/Windows 部分直接调用系统命令
